### ISSUE TITLE
ci-cgroupv1-containerd-node-e2e-serial-ec2 is failing

### ISSUE THREAD

**Issue by dims** [kubernetes-sigs/provider-aws-test-infra#17]
https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-e2e-serial-ec2

cc @upodroid @tzneal

**Comment by dims** [comment]
https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-e2e-serial is also failing but not as badly

**Comment by tzneal** [comment]
My initial guess was going to be a driver mismatch, then I saw your PR at https://github.com/kubernetes-sigs/provider-aws-test-infra/commit/fe2e42deef10dcb362aeb0b52584f97a6d227018.  When I was running on the AL2 AMIs, I set `--cgroup-driver=systemd` as part of the TEST_ARGS

**Comment by dims** [comment]
xref: https://github.com/kubernetes/test-infra/pull/29858

**Comment by dims** [comment]
we are down to a few flakes. let's close this out for now. https://testgrid.k8s.io/sig-node-ec2
